// Generated by Selenium IDE

import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;

public class SearchAndShowTest extends TestEnvironment {

  @Test
  public void search() {
    driver.get("http://116.62.181.135:8080/achieveit/#/projectList");
    driver.findElement(By.cssSelector(".el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-input__inner")).sendKeys("test project");
    driver.findElement(By.cssSelector(".el-button--default")).click();
  }

  @Test
  public void show() {
    driver.get("http://116.62.181.135:8080/achieveit/#/projectList");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver
        .findElement(By.cssSelector(".el-table__row:nth-child(1) > .el-table_1_column_1 > .cell"))
        .click();
    driver
        .findElement(By.cssSelector(".el-table__row:nth-child(1) > .el-table_1_column_2 > .cell"))
        .click();
    driver
        .findElement(By.cssSelector(".el-table__row:nth-child(2) > .el-table_1_column_1 > .cell"))
        .click();
  }
}
